### ISSUE TITLE
Not working on Big Sur

### ISSUE THREAD

**Issue by oliver-ni** [feross/SpoofMAC#101]

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.

**Comment by feross** [comment]
Apple seems to enable and disable MAC address changing between releases and it's not clear why. See: https://github.com/feross/SpoofMAC/issues/87

If there's something that we can do to fix this in this library, please post here.

**Comment by yangxyo** [comment]
not woking on en3
```
ifconfig: ioctl (SIOCAIFADDR): Operation not supported on socket
```

**Comment by JustRLC** [comment]
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
Works like a charm on MacOS version`Big Sur 11.0.1 (20B29)`

Seems this is an ongoing issue with Macbook 2018 and later

**Comment by feross** [comment]
Works for me on Big Sur 11.0.1 (20B29) from a MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports). I'm not sure there's anything for us to do here.

**Comment by lucis** [comment]
Adding here that it doesn't work for Big Sur 11.0.1 on MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)
