### ISSUE TITLE
MAC not changed

### ISSUE THREAD

**Issue by nkrh** [feross/SpoofMAC#35]
Hi,

I'm using Ralink RT5390R 802.11bgn

Nick

**Comment by jpalcantara** [comment]
Hello,
I installed the following on my mac book running 10.10.4  pip install SpoofMAC and easy_install SpoofMAC and I also wanted to automate this.
if I run sudo spoof-mac.py randomize en1 it does what it does
then I run spoof-mac.py list and shows what it's supposed to.
But I installed the Startup Installation . And restarted my system and there is no changes on the WIFI card and also is the local.macspoof.plist supposed to be empty?
