### ISSUE TITLE
No results on 3.17.6-1-ARCH Linux

### ISSUE THREAD

**Issue by cannapages** [feross/SpoofMAC#41]
It might be my hardware or system configuration limitation because I have tried multiple methods with no result. However I though I would mention this and see if there is something that could be done to accomplish mac spoofing in my environment.

When I run
$ sudo spoof-mac.py list
It has no output

$ ifconfig
// Other devices removed for brevity
wlp4s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether a0:88:69:0c:87:67  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by pteek** [comment]
Your system's ifconfig output is different than what is handle in SpoofMAC. If you have experience with regex and pyhton, you can write a ifconfig parser for ARCH linux.

Send a pull when you have it working.

**Comment by pteek** [comment]
What is the output of platform.linux_distribution() in Python on your system?

**Comment by feross** [comment]
Closing because of lack of information. @cannapages, if you decide to reply, feel free to re-open the issue.
