### ISSUE TITLE
Administrative Privileges Error

### ISSUE THREAD

**Issue by nateurwin** [feross/SpoofMAC#48]
Started with the run command: `cmd /user:admin`
```
C:\windows\system32>spoof-mac.py randomize Ethernet
Error: Must run this with administrative privileges to set MAC addresses
```
My user account is the primary administrator account.

**Comment by feross** [comment]
Did you start your terminal as an administrator?

**Comment by nateurwin** [comment]
Disregard this issue! It works when I right-click `cmd.exe` and click `Run as administrator` but for some reason I can't enter an elevated command prompt using the `runas /user:administrator cmd` command. I'm on Windows 8, so it probably has something to do with that. Thanks for the quick reply!

**Comment by feross** [comment]
No problem!
