### ISSUE TITLE
Sppofmac not automating

### ISSUE THREAD

**Issue by jpalcantara** [feross/SpoofMAC#49]
Hello,
I installed the following on my mac book running 10.10.4 pip install SpoofMAC and easy_install SpoofMAC and I also wanted to automate this.
if I run sudo spoof-mac.py randomize en1 it does what it does
then I run spoof-mac.py list and shows what it's supposed to.
But I installed the Startup Installation . And restarted my system and there is no changes on the WIFI card and also is the local.macspoof.plist supposed to be empty?

**Comment by feross** [comment]
Take a look at the system Console after startup. You might find some helpful error logs in there.

**Comment by jpalcantara** [comment]
There are none that I can see!

**Comment by feross** [comment]
I'm sorry - I just don't have enough information to help you debug this.

**Comment by jpalcantara** [comment]
But I wanted to know does the the local.macspoof.plist supposed to be empty?

**Comment by feross** [comment]
No, you can see what's supposed to be in it here: https://github.com/feross/SpoofMAC/blob/master/misc/local.macspoof.plist

**Comment by jpalcantara** [comment]
Is the content is supposed to be populated automatically or do I need to add this?

**Comment by feross** [comment]
You need to create the file.

**Comment by jpalcantara** [comment]
Well it is now working!  thanks

**Comment by feross** [comment]
Great!
