### ISSUE TITLE
Automatically reconnect to last connected network?

### ISSUE THREAD

**Issue by hubdotcom** [feross/SpoofMAC#50]
This would be fantastic if it was possible!

**Comment by raincoats** [comment]
Interesting question! I'm not really 100% on github etiquette, but I just tried it out and I think it's probably ok to share, even though this isn't my project.

on OS X this seems to work (but it really seems like it would break easily):

```shell
wifi=$(networksetup -getairportnetwork en0 | sed 's/.*: //')
sudo spoof-mac.py randomize en0
networksetup -setairportnetwork en0 $wifi
```

**Comment by feross** [comment]
@raincoats Cool trick! Can someone send a pull request and add this feature? Thanks!
