### ISSUE TITLE
Change MAC address of bluetooth adapter

### ISSUE THREAD

**Issue by and7ey** [feross/SpoofMAC#51]

**Comment by and7ey** [comment]
Could you please add a functionality to change Mac-address of Bluetooth?
Thanks in advance.

**Comment by feross** [comment]
Happy to accept this as a PR if it doesn't complicate the codebase too much.

**Comment by feross** [comment]
Looks like a PR isn't forthcoming.

**Comment by itsmesac** [comment]
Is this implemented yet? Looks like a nice-to-have feature.
