### ISSUE TITLE
Issue when showing all Wi-Fi interface names

### ISSUE THREAD

**Issue by shravan14k** [feross/SpoofMAC#52]
The program in the "Show only Wi-Fi interfaces" mode, currently only shows those interfaces that are exactly named "Wi-Fi". But in my PC, I often end up having names like "Wi-Fi 2", "Wi-Fi 3" etc (after changing network configs). I guess we should change [line 352 in interface.py](https://github.com/feross/SpoofMAC/blob/master/spoofmac/interface.py#L352) something like,

`if port.lower() in wireless_port_names:`
to
`if port.lower().startswith("wi-fi") or (port.lower() == "airport"):`

**Comment by feross** [comment]
Thanks opening this issue. Can you send a PR that fixes it. I'll merge and release.
