### ISSUE TITLE
OUI set to a VMware

### ISSUE THREAD

**Issue by rwsnyder** [feross/SpoofMAC#54]
The randomization protocol automatically sets the first three hexadecimal values the same every time (00:05:69). This is not particularly random, and tells any device that you are either operating a VMware virtual machine or are using this software to spoof your MAC. I read through the source code and saw that you chose this range because it would have a very low chance of colliding with another device on the network (one in 16.7 million for any other random VMware MAC), however I would recommend throwing in some code to switch between a couple of different possible VM designations:
00:50:56, 00-0C-29 for manually assigned VMware MACs
00:16:3E for Xen VMs
00-03-FF Microsoft Hyper-V, Virtual Server, Virtual PC
00-1C-42 Parallells 
00-0F-4B Virtual Iron 4
08-00-27 Sun Virtual Box

Doing this will increase the anonymity without greatly increasing the risk of collision.

**Comment by feross** [comment]
Released as 2.0.6. https://pypi.python.org/pypi/SpoofMAC/
