### ISSUE TITLE
MAC OS 10.11.1 (15B42)

### ISSUE THREAD

**Issue by jpalcantara** [feross/SpoofMAC#57]
Hello,

  Are there any reports with the WIFI loosing it's ip address.  The script Spoofmac worked flawlessly and the connectivity was stable and then I upgraded to MAC OS 10.11.1 since then I lose the connectivity.
  I am not entirely sure that the ^problem is stemming from Spoofmac.  

  And I may need to uninstall the script to further troubleshoot the issue.

**Comment by feross** [comment]
I haven't had this issue and I was using OS X 10.11.1 when it was the latest version. I'm now on 10.11.2.

Has it worked better for you on 10.11.2?
