### ISSUE TITLE
Randomizing "Thunderbolt 1" and "Thunderbolt 2" on OSX 10.11

### ISSUE THREAD

**Issue by adrianbrink** [feross/SpoofMAC#63]
Hi,
when running 'list', it shows me that both Thunderbolt connections run on en1 and en2, respectively. However when I try to randomize en1 and en2 there is no change, or at least 'list' doesn't show any change.

Any idea why that could be happening?

Thank you for this tool. It's awesome.

**Comment by feross** [comment]
Thunderbolt can't be randomized because it's not ethernet. If you know a way to fix this, feel free to send a PR!
