### ISSUE TITLE
Not working with windows 10

### ISSUE THREAD

**Issue by command-paul** [feross/SpoofMAC#64]
Tried running your script on a windows 10 machine with an Intel 8260 WiFi module, The mac address did not change ..

**Comment by feross** [comment]
This library is not actively maintained anymore. You're welcome to send a PR to fix the issue.

**Comment by CCninja86** [comment]
I might see if I can figure it out when I have the chance. It would be nice to have a script for Windows 10. You'll just have to set it manually for now.

**Comment by CCninja86** [comment]
I've just noticed that when you change your MAC address in the network adapter properties, it does change the MAC address, but the new MAC address is still not visible from ipconfig in the command line. It might be that this script does actually work with Windows 10, but the change isn't visible. I'll investigate this further at a later date and update with the results.
