### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x94 in position 20: ordinal not in range(128)

### ISSUE THREAD

**Issue by bigzie** [feross/SpoofMAC#65]
Hi!
I usually use osX and Linux - but I have a small project and a group of ppl that need to spoof there MAC-adres and keep getting a **UnicodeDecodeError: 'ascii' codec can't decode byte 0x94 in position 20: ordinal not in range(128)** error. Tried to use UTF-8 but keep getting the same error.

Any tips?

> 
> PS C:\program files (x86)\Python35-32\Scripts> python spoof-mac.py list
> Traceback (most recent call last):
>   File "spoof-mac.py", line 138, in <module>
>     sys.exit(main(arguments, root_or_admin))
>   File "spoof-mac.py", line 76, in main
>     list_interfaces(args, spoofer)
>   File "spoof-mac.py", line 56, in list_interfaces
>     for port, device, address, current_address in spoofer.find_interfaces(targets=targets):
>   File "C:\Program Files (x86)\Python35-32\lib\site-packages\spoofmac\interface.py", line 266, in find_interfaces
>     output = self.get_ipconfig_all()
>   File "C:\Program Files (x86)\Python35-32\lib\site-packages\spoofmac\interface.py", line 230, in get_ipconfig_all
>     return result.decode('ascii')
> UnicodeDecodeError: 'ascii' codec can't decode byte 0x94 in position 20: ordinal not in range(128)

**Comment by bigzie** [comment]
Answer found in: **https://github.com/feross/SpoofMAC/issues/56**

**Comment by SadrulAmin** [comment]
Answer please (above question)?
