### ISSUE TITLE
Doesn't work on macOS Sierra

### ISSUE THREAD

**Issue by soheil** [feross/SpoofMAC#67]

**Comment by feross** [comment]
What happens? Any error you can share?

**Comment by sheriferson** [comment]
I think it works, at least on the 10.12 GM that was released yesterday (Sep 8).

After running

```bash
$ spoof-mac --version
2.1.1
$ sudo spoof-mac randomize wi-fi
```

I was disconnected from the hotspot I was on and had to re-connect.

and I get this as list of devices:

```bash
$ spoof-mac list
- "Wi-Fi" on device "en0" with MAC address [something] currently set to [something else]
. . .
```

Is there a way of testing further whether the spoofing was working other than what I reported?

**Comment by feross** [comment]
The output of `spoof-mac list` comes directly from the underlying ifconfig command so it looks like it's working now. Great news!
