### ISSUE TITLE
Running On Windows with py2 or py3 same Error

### ISSUE THREAD

**Issue by MomenFathi** [feross/SpoofMAC#71]
when i only give the command "list"

![capture](https://cloud.githubusercontent.com/assets/8422599/21323363/bb6c8cfe-c625-11e6-8ae5-b6f0e8de9305.PNG)

**Comment by feross** [comment]
What version of Python?

**Comment by MomenFathi** [comment]
i've tried both 2.7 and 3

both 2016 !

**Comment by feross** [comment]
@MomenFathi I think this is because you have non-ascii characters in the output of the command to list your interfaces. Do you mind me asking if you're using a non-English language on your OS?

**Comment by feross** [comment]
I don't have the expertise or time to fix this right now, so I'll defer to the other collaborators @TkTech, @pteek, and @cjbarker.

**Comment by MomenFathi** [comment]
yes i'm using Arabic in my OS preside English . 
well i wish you could do something about this , cause i'm out of options about spoofing the mac address in Windows OS here .. i tried all the programs that i could find , 

any ways thanks for replying on my issue and good luck fixing it , and i hope it will be soon .

**Comment by pteek** [comment]
Please post output of "ipconfig /all" on your system.

**Comment by MomenFathi** [comment]
C:\Users\Momen>ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : Momen-PC
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Mixed
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   System Quarantine State . . . . . : Not Restricted


Wireless LAN adapter Wireless Network Connection 4:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Virtual WiFi Miniport Adapter #2
   Physical Address. . . . . . . . . : 00-C0-CA-72-40-1C
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Wireless Network Connection 3:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Realtek RTL8187 Wireless 802.11b/g 54Mbps USB 2.0 Network Adapter
   Physical Address. . . . . . . . . : 00-C0-CA-72-40-1C
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Ethernet adapter Local Area Connection 4:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : ltt.ly
   Description . . . . . . . . . . . : EchoLife WiMAX USB Modem Device #2
   Physical Address. . . . . . . . . : 00-25-68-A6-5D-19
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter isatap.{D431AABA-496E-4D5B-8EAD-9EED9A587BC2}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter isatap.{8574D7B5-E3EB-4B5B-8194-7510BEEB545D}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter #2
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter isatap.ltt.ly:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter #4
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

C:\Users\Momen>
