### ISSUE TITLE
Belkin USB-C LAN does not work

### ISSUE THREAD

**Issue by andykingway** [feross/SpoofMAC#72]
I am using Macbook pro late 2016 with Belkin USB-C LAN adapter. 
It doesn't work on mac spoofing. 
There are no errors after command issued. The mac address stays the same.
> sudo spoof-mac set xx:xx:xx:xx:xx:xx en7
> spoof-mac list
...
- "Belkin USB-C LAN" on device "en7" with MAC address xx:xx:xx:xx:xx:xx
...

Thanks.

**Comment by cjbarker** [comment]
Can you open a terminal and run the following command.  Please copy/paste output from your Macbook with Belkin adapter enabled.

`networksetup -listallhardwareports`

**Comment by feross** [comment]
Also, can you try running `sudo spoof-mac randomize en7` and see if that works? I suspect you might be trying to set it to an invalid mac address, and it's just being ignored instead.

**Comment by andykingway** [comment]
Thank you for the response, following are the command that I issued and results.

> networksetup -listallhardwareports

Hardware Port: LPSS Serial Adapter (1)
Device: lpss-serial1
Ethernet Address: N/A

Hardware Port: LPSS Serial Adapter (2)
Device: lpss-serial2
Ethernet Address: N/A

Hardware Port: Belkin USB-C LAN
Device: en7
Ethernet Address: 58:ef:68:13:8b:9e

Hardware Port: Wi-Fi
Device: en0
Ethernet Address: f4:0f:24:34:c6:0a

Hardware Port: Bluetooth PAN
Device: en5
Ethernet Address: f4:0f:24:16:eb:c5

Hardware Port: Thunderbolt 1
Device: en1
Ethernet Address: 7e:00:a0:c0:72:00

Hardware Port: Thunderbolt 1
Device: en2
Ethernet Address: 7e:00:a0:c0:72:04

Hardware Port: Thunderbolt 13
Device: en3
Ethernet Address: 7e:00:a0:c0:72:01

Hardware Port: Thunderbolt 14
Device: en4
Ethernet Address: 7e:00:a0:c0:72:05

Hardware Port: Thunderbolt Bridge
Device: bridge0
Ethernet Address: 7e:00:a0:c0:72:00

VLAN Configurations

>spoof-mac list
- "LPSS Serial Adapter (1)" on device "lpss-serial1"
- "LPSS Serial Adapter (2)" on device "lpss-serial2"
- "Belkin USB-C LAN" on device "en7" with MAC address 58:EF:68:13:8B:9E
- "Wi-Fi" on device "en0" with MAC address F4:0F:24:34:C6:0A
- "Bluetooth PAN" on device "en5" with MAC address F4:0F:24:16:EB:C5
- "Thunderbolt 1" on device "en1" with MAC address 7E:00:A0:C0:72:00
- "Thunderbolt 1" on device "en2" with MAC address 7E:00:A0:C0:72:04
- "Thunderbolt 13" on device "en3" with MAC address 7E:00:A0:C0:72:01
- "Thunderbolt 14" on device "en4" with MAC address 7E:00:A0:C0:72:05
- "Thunderbolt Bridge" on device "bridge0" with MAC address 7E:00:A0:C0:72:00
>sudo spoof-mac randomize en7
Password:
>spoof-mac list
- "LPSS Serial Adapter (1)" on device "lpss-serial1"
- "LPSS Serial Adapter (2)" on device "lpss-serial2"
- "Belkin USB-C LAN" on device "en7" with MAC address 58:EF:68:13:8B:9E
- "Wi-Fi" on device "en0" with MAC address F4:0F:24:34:C6:0A
- "Bluetooth PAN" on device "en5" with MAC address F4:0F:24:16:EB:C5
- "Thunderbolt 1" on device "en1" with MAC address 7E:00:A0:C0:72:00
- "Thunderbolt 1" on device "en2" with MAC address 7E:00:A0:C0:72:04
- "Thunderbolt 13" on device "en3" with MAC address 7E:00:A0:C0:72:01
- "Thunderbolt 14" on device "en4" with MAC address 7E:00:A0:C0:72:05
- "Thunderbolt Bridge" on device "bridge0" with MAC address 7E:00:A0:C0:72:00
>

**Comment by feross** [comment]
I'm inclined to guess that your Belkin device just doesn't support having it's MAC address changed. But maybe @cjbarker has a thought for what could be the problem.

**Comment by andykingway** [comment]
Thank you for the information.
