### ISSUE TITLE
Startup Setting preiosly set mac?

### ISSUE THREAD

**Issue by shirshak55** [feross/SpoofMAC#83]
Suppose I have set my mac to aa:aa:aa:aa:aa:aa now. But readme startup will take just randomize mac is there anything to do for previously set mac. ?

**Comment by feross** [comment]
Change the command that is run on startup from the `randomize` command to the `set` command.

**Comment by shirshak55** [comment]
@feross but it will set new mac not previously set mac right?

**Comment by feross** [comment]
You can run whatever command you want on startup. If you run the command `spoof-mac.py set 00:00:00:00:00:00 en0` then it will set the MAC address accordingly on startup.
