### ISSUE TITLE
Not work on OSX 10.13.3?

### ISSUE THREAD

**Issue by modkzs** [feross/SpoofMAC#85]
I update my system to 10.13.3, it seems not work?

**Comment by eaglejs** [comment]
Just used it today, i'm on 10.13.3 and it works. What are your steps to using it? :) 

Make sure you are running the command on the proper network card. for example. on my macbook pro 2017. I am changing the mac address of my wifi network card. To do this, I simply ran...

`sudo spoof-mac.py set 4e:53:50:4f:4f:40 en0`

i'm setting the mac address to what I want on my en0 wifi card.

You can easily type `ifconfig` to see all of the network interfaces that you have.

For me, I had to turn off the wifi, run the above command, then turn it back on for it to work properly.

**Comment by modkzs** [comment]
I retry it after reboot my machine, and it worked.
