### ISSUE TITLE
automatically randomize MAC a linux startup

### ISSUE THREAD

**Issue by yougz11** [feross/SpoofMAC#86]
Hello,
First, thanks for your job. I did it successfully on mac os x and it works fine ;)
Now i would like to set a random MAC at kali linux startup under VM (vmware) but even when i m trying to follow your steps to the T it fails. Do you have a solution please ?
Thanks a lot

**Comment by feross** [comment]
There are no instructions in the readme for automatic startup on other OSs. You'll have to figure it out for yourself. This is the Linux way of life. 😁
