### ISSUE TITLE
Possible launchd plist file fix.

### ISSUE THREAD

**Issue by dumol** [feross/SpoofMAC#95]
Mac Mini late 2012 edition with up to date macOS 10.14 Mojave.

Had to add this section to get the job done:
```
    <key>KeepAlive</key>
        <dict>
            <key>SuccessfulExit</key>
                <false/>
        </dict>
    <key>ThrottleInterval</key>
        <integer>10</integer>
```

Could be because the network card is not available at the time it is executed for the first time? I'm not that knowledgeable when it comes to launchd.

Thanks!

**Comment by feross** [comment]
Thanks for sharing. I think this runs the command every 10 seconds? That seems like a brute force way to solve the problem. Let us know if you (or anyone else) finds a better way and we'll update the docs.
