### ISSUE TITLE
prerequisites for installation

### ISSUE THREAD

**Issue by ghost** [feross/SpoofMAC#97]
Hey,

I'm on a MacOS Catalina (10.15.2) trying to install SpoofMAC.

2 questions:

1) Tried installing using the `% git clone git://github.com/feross/SpoofMAC.git` command, but was greeted with:

xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.

So, does this installation require xCode? No info on this in the installation instructions. 

2) Also, I assume I won't have to amend the consequent installation commands by adding a pathname if I am using the MacOS' native Python 3?

**Comment by TkTech** [comment]
This doesn't have anything to do with SpoofMAC. You're using the git provided by OS X (rather than say homebrew) which comes from xcode, but haven't set up xcode.

**Comment by ghost** [comment]
... so I’ll interpret this as “yes, you need xCode”. And it has to do with installing SpoofMAC? :)
In the same way a “click Control Panel” doesn’t really have anything to do with SpoofMAC but is relevant to the installation, and is included. ;) 

Thanks, I guess.
