### ISSUE TITLE
Cannot change Mac Address on: MacBook Air Early 2015, on 10.15.4 or 10.15.3

### ISSUE THREAD

**Issue by elihwyma** [feross/SpoofMAC#98]
Ever since updating to 10.15.3 it stopped working, so I thought going to 10.15.4 might fix it, but no, it still doesn't work. 

When using ifconfig, it changes here, but then when alt-clicking Wi-Fi it's still the original unchanged address

Also not working now on 10.15.1

**Comment by feross** [comment]
This is out of the control of this library. There are certain versions of macOS that disabled changing the MAC address for some unknown reason.
