### ISSUE TITLE
Not working as per instructions

### ISSUE THREAD

**Issue by johnstonesnow** [feross/SpoofMAC#99]
MBP Mid 2012 running High Sierra. 

I ran the pip and easy_install commands but it fails. permission denied /Library...... 
"Perhaps your account does not have write access to this directory". 

Any help appreciated, I am obviously not too used to using CLI. 

I tried it with sudo and same problem

**Comment by feross** [comment]
This is not a support forum – this is for bugs with SpoofMAC. Please try StackOverflow.
